### ISSUE TITLE
[2.0] validator isNaN 변경

### ISSUE THREAD

**Issue by moonformeli** [ex-em/EVUI#418]
```ts
// src > components > input > input.number.vue
// line 121
 precision: {
   type: Number,
   default: 1,
   validator(value) {
      return !isNaN(Number(value)) && value >= 0 && value <= 100;
   },
},
```

위의 예제는 `validator => (value: []): boolean` 일 때 다음과 같은 경우에서 예외가 발생합니다.

```js
isNaN(Number([])) // false
```

아래와 같이 바꾸는 것도 하나의 방법이라고 보여집니다

```js
validator2 = value => {
  if (typeof value === 'number' && !Number.isNaN(value)) {
    return true;
  }
  return false;
}

...

validator([]) // true;
validator2([]) // false;
```

추가로, `isNaN` 보다 `Number.isNaN` 이 코드의 목적과 더 맞아 보입니다.
`isNaN` 은 `window` 에 포함된 메소드 이지만
`Number.isNaN` 은 `Number` 에 포함된 메소드입니다.
두 메소드는 차이점이 존재하고 NaN 을 거르는 목적에선 `Number.isNaN` 을 사용하는 것이 더 권장되는 바입니다.
ref: https://stackoverflow.com/questions/33164725/confusion-between-isnan-and-number-isnan-in-javascript

**Comment by KimBohwan** [comment]
Hi moonformeli !  Come on man.

**Comment by darkstyles** [comment]
좋은 피드백이네요  
number가 아닌 값을 굳이 체크할 필요없이 걸러내는것이 맞죠

**Comment by moonformeli** [comment]
뷰에서 타입스크립트 도입 생각이 있으시면 아래처럼도 가능합니다.
(물론 상황에 맞게 수정해야함)

// ts 3.7 미만
```ts 
validator: (val: any) => {
  return Number.isNaN(val);
}
```

// ts 3.7+
```ts
// 더 강력한 타입체킹 가능

// 어딘가의_파일.ts
const assert = <T extends any>(val:T, msg?: string): asserts val is T => {
  if (typeof val !== T) {
    throw new Error(msg);
  }
}

...

validator: (val: any) => {
  assert(val);
  return true;
}
```
