### ISSUE TITLE
[2.0] keycode 패키지 설치

### ISSUE THREAD

**Issue by moonformeli** [ex-em/EVUI#419]
```
> npm i -D keycode
```
license: MIT
ref: https://github.com/timoxley/keycode

### 이유

너무 알아보기 힘듦
```js
if (which === 20) {
  ...
}
```

```js
// better
import * as keycode from 'keycode';
// const keycode = require('keycode');

if (which === keycode('caps lock')) {
  ...
}
```

**Comment by moonformeli** [comment]
선택이긴한데 저렇게 문자로 사용하는 것조차 조금 꺼려진다 하면 아래와 같이도 가능할겁니다.

```js
import * as keycode from 'keycode';

export default class Keycode {
  static CAPS_LOCK(key) {
    return key === keycode('caps lock');
  }
}

...

import Keycode from '../your_path.js';

if (Keycode.CAPS_LOCK(which)) {
  ...
}
```

장점: 뭔가 좀 더 `enum` 같은 느낌으로 쓸 수 있음
단점: 적어도 클래스를 import 해야하니까 귀찮을 수도 있음

static 으로 메소드를 꾸미는게 더 나은 이유는, `keycode` 를 사용하고 있는 코드가 많다면 굳이 클래스를 생성해서 들고 다녀야 할 특정한 이유가 없습니다. 그래도 나는 정 만들어서 갖고 다녀야겠다 그러면 싱글톤으로 만드는게 나아 보입니다.

**Comment by darkstyles** [comment]
키코드는 위처럼 처리하면 확실히 가독성측면에서 좋겟네요.  
아직까지는 키코드에 대한 부분을 컴포넌트에 반영을 하지 않아 처리 시 반영하도록 할게요
