### ISSUE TITLE
[2.0] 큰 숫자는 지수 활용

### ISSUE THREAD

**Issue by moonformeli** [ex-em/EVUI#420]
https://github.com/ex-em/EVUI/blob/223ba78653d06e0550c8e231648f43cf22f565bf/src/components/chart/helpers/helpers.util.js#L31

1000000000000000 는 한 눈에 봐서 얼마나 큰지, 적어도 0이 뒤에 몇 개인지 알기 힘듭니다.
아래와 같이 바꾸는게 가독성에 더 좋다에 한표입니다

```js
1000000000000000 => 10e14 (혹은 1e15)

(15개) 100...00 === 10e14 === 1e15 // true
```

아래는 지금 이슈에 대해 현재 `stage3` 에 올라와 있는 ecmascript 예비 신규스펙입니다.
es11, es12 정도에 추가될 것 같고 현재 테스트까지 다 끝난 상태입니다.
ref: https://github.com/tc39/proposal-numeric-separator

만약 바벨을 사용하고 있다면 아래의 플러그인을 추가하면 됩니다.
ref: https://babeljs.io/docs/en/babel-plugin-proposal-numeric-separator

```
> npm i -D @babel/plugin-proposal-numeric-separator
```
```js
// .babelrc  
{
  "presets": [
    ["env", {
      "modules": "umd",
      "targets": {
        "browsers": ["> 1%", "last 2 versions", "not ie <= 8"]
      }
    }],
    "stage-2"
  ],
  "plugins": [
  "syntax-dynamic-import", 
  "transform-vue-jsx",
   "transform-runtime", 
  **"@babel/plugin-proposal-numeric-separator"**
],
  "env": {
    "test": {
      "presets": ["env", "stage-2"],
      "plugins": ["transform-vue-jsx", "istanbul"]
    }
  }
}
```

**Comment by moonformeli** [comment]
바벨 버전을 7로 올려야하는데 현재 `6.26.3` 이라 바벨로 적용은 할 수 없음.
바벨을 올리면서 사이드 이펙트가 어떤게 생길지 몰라 대대적인 점검 필요
메소드로 아래와 같이 따로 만들던지 해야할 듯.

```js
const millions = v => {
  return 1e6 * v;
}

const billions = v => {
  return 1e9 * v;
}
```

**Comment by jwlee1108** [comment]
해당 부분은 코드 수정 시 적용해보도록 하겠습니다. 감사합니다.
