### ISSUE TITLE
[2.0] 메소드 리팩토링

### ISSUE THREAD

**Issue by moonformeli** [ex-em/EVUI#429]
비지니스 로직에 문제가 생기지 않는 선에서, 
가독성에 우선을 둔 메소드 리팩토링을 진행하는 것에 대한 의견을 제시합니다.
아래 내용에 대해 진행해도 상관이 없다면 진행해보고자 합니다.

### 내용
1. `isNaN` -> `Number.isNaN`
2. truthy validation check -> `truthy` 혹은 `truthyNumber` 혹은 `truthyWhatever` 형식의 메소드 추가 및 사용
3. `indexOf() !== -1` -> `includes()` 혹은 `some()` 으로 변경
4. 불필요한 string literal 표현 제거
5. 타입 검사 강화 및 arguments 타입 주석 추가 (* instead of typescript)
6. css color 공통 상수 (scss 로 컬러 프리셋이 추가되기 전까지 사용)
7. 기타

**Comment by moonformeli** [comment]
> 비지니스 로직에 문제가 생기지 않는 선에서,
> 가독성에 우선을 둔 메소드 리팩토링을 진행하는 것에 대한 의견을 제시합니다.
> 아래 내용에 대해 진행해도 상관이 없다면 진행해보고자 합니다.
> 
> ### 내용
> 1. `isNaN` -> `Number.isNaN`
> 2. truthy validation check -> `truthy` 혹은 `truthyNumber` 혹은 `truthyWhatever` 형식의 메소드 추가 및 사용
> 3. `indexOf() !== -1` -> `includes()` 혹은 `some()` 으로 변경
> 4. 불필요한 string literal 표현 제거
> 5. 타입 검사 강화 및 arguments 타입 주석 추가 (* instead of typescript)
> 6. css color 공통 상수 (scss 로 컬러 프리셋이 추가되기 전까지 사용)
> 7. 기타

**Comment by darkstyles** [comment]
6번 사항에 대해서는 현재 공통작업을 내부적으로 진행중이라 제외해주세요
나머지 사항에 대해서는 검토를 해보도록 할게요

**Comment by KimBohwan** [comment]
아직 개발이 완성되지 않은 상태에서 리펙토링은 효율이 좀 떨어져 보입니다. 
어느정도 개발적 안정성이 올라왔을때 검토하겠습니다.
