### ISSUE TITLE
[2.0] lodash 의 debounce 수정 건의

### ISSUE THREAD

**Issue by moonformeli** [ex-em/EVUI#473]
지금 설치된 lodash 의 버전은 4 인데 여기서 사용되는 코드가 조금 올드합니다.

```ts
function leadingEdge(time) {
  // Reset any `maxWait` timer.
  lastInvokeTime = time;
  // Start the timer for the trailing edge.
  timerId = setTimeout(timerExpired, wait);
  // Invoke the leading edge.
  return leading ? invokeFunc(time) : result;
}
```

현재 항상 `setTimeout` 만 사용하고 있기 때문에 rAF 로 교체된 메소드를 사용하는게 성능면에서 훨씬 유리합니다. 사파리를 지원하지 않는 이상 rAF 를 사용함으로 인해 렌더링 스텝에서 사이드 이펙트가 발생할 확률은 0% 입니다. 현재 5 버전 부터는 rAF 가 적용된 코드가 배포될 예정이지만 로대시는 워낙에 메이저를 올리는 주기가 느리기때문에 프로젝트 코드 내에서 오버라이드로 바꾸는 형식이 가장 좋아보입니다.

rAF 가 적용된 debounce 의 코드 일부입니다. 
자세한 코드 현황은 [링크](https://github.com/lodash/lodash/blob/master/debounce.js)를 참조하시기 바랍니다. 
```ts
// Bypass `requestAnimationFrame` by explicitly setting `wait=0`.
const useRAF = (!wait && wait !== 0 && typeof root.requestAnimationFrame === 'function')

...

function startTimer(pendingFunc, wait) {
  if (useRAF) {
    root.cancelAnimationFrame(timerId)
    return root.requestAnimationFrame(pendingFunc)
  }
  return setTimeout(pendingFunc, wait)
}
```
lodash 에서도 설명한 것처럼 의도적으로 delay 를 0 으로 넘겨 setTimeout 을 사용하려는 의도가 아닌 이상 사용법은 달라지는게 없습니다. debounce 코드만 오버라이드해서 사용하면 끝입니다.

**Comment by moonformeli** [comment]
위 코멘트의 내용을 약간만 정정하겠습니다.
일반적인 경우 사이드 이펙트를 발생시킬 확률이 0% 라는 뜻입니다.
현재 적용된 로직에서 setTimeout 에 들어가는 콜백이 해당 tick 을 훨씬 초과해 그 다음 tick 의 렌더링을 뒤로 미뤄버릴 정도로 오랜 시간이 걸리는 작업이 아니라면 0%가 맞고, 그렇게나 오래걸리는 작업인 경우엔 0%가 아닐수도 있습니다

**Comment by darkstyles** [comment]
수정 건의하신 내용에서 오버라이드를 어떤식으로 한다는것인지 잘 이해가 안가네요.  
debounce 함수 오버라이드를 위해 전체 lodash를 import 하여 prototype으로 해당 메소드를 오버라이드 한다면 트리쉐이킹에는 문제가 없을까요?

**Comment by moonformeli** [comment]
제가 표현을 좀 잘못 한 것 같네요
그냥 유틸함수로 빼서 만드는거로 충분할 것 같습니다

**Comment by darkstyles** [comment]
음.. 오버라이드 적용 방식에 대해서 제가 이해한 내용이 맞나요?  
사실 그게 잘 판단이 안서서 질문한거라서요

**Comment by moonformeli** [comment]
오버라이드라는 단어를 제가 잘못 사용한것같아요.
유틸 함수로 만들어서 사용하는게 나을 것 같습니다

**Comment by darkstyles** [comment]
네 알겠어요  
위 내용 참고해서 유틸쪽에 만들어서 사용하도록 해볼게요

**Comment by darkstyles** [comment]
PR이 되어서 이슈 닫을게요
